// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "in": "header",
            "name": "X-API-KEY",
            "description": "Optional API key for elevated rate limit tier (1 000 req/min). Leave empty to use the anonymous tier (60 req/min, identified by IP)."
        }
    },
    "paths": {
        "/cities/{id}": {
            "get": {
                "description": "Get specific city/regency details by its code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cities"
                ],
                "summary": "Get city by ID",
                "security": [{"ApiKeyAuth": []}],
                "parameters": [
                    {
                        "type": "string",
                        "description": "City Code (e.g. 11.01)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Region"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized — invalid API key",
                        "schema": {
                            "$ref": "#/definitions/model.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.APIErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests — rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/model.RateLimitError"
                        }
                    }
                }
            }
        },
        "/cities/{id}/districts": {
            "get": {
                "description": "Get list of districts (Kecamatan) in a specific city",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "cities"
                ],
                "summary": "Get districts in city",
                "security": [{"ApiKeyAuth": []}],
                "parameters": [
                    {
                        "type": "string",
                        "description": "City Code (e.g. 11.01)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Region"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized — invalid API key",
                        "schema": {
                            "$ref": "#/definitions/model.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.APIErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests — rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/model.RateLimitError"
                        }
                    }
                }
            }
        },
        "/districts/{id}": {
            "get": {
                "description": "Get specific district details by its code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "districts"
                ],
                "summary": "Get district by ID",
                "security": [{"ApiKeyAuth": []}],
                "parameters": [
                    {
                        "type": "string",
                        "description": "District Code (e.g. 11.01.01)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Region"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized — invalid API key",
                        "schema": {
                            "$ref": "#/definitions/model.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.APIErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests — rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/model.RateLimitError"
                        }
                    }
                }
            }
        },
        "/districts/{id}/villages": {
            "get": {
                "description": "Get list of villages (Kelurahan/Desa) in a specific district",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "districts"
                ],
                "summary": "Get villages in district",
                "security": [{"ApiKeyAuth": []}],
                "parameters": [
                    {
                        "type": "string",
                        "description": "District Code (e.g. 11.01.01)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Region"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized — invalid API key",
                        "schema": {
                            "$ref": "#/definitions/model.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.APIErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests — rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/model.RateLimitError"
                        }
                    }
                }
            }
        },
        "/states": {
            "get": {
                "description": "Get list of all provinces in Indonesia",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "states"
                ],
                "summary": "Get all states",
                "security": [{"ApiKeyAuth": []}],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Region"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized — invalid API key",
                        "schema": {
                            "$ref": "#/definitions/model.UnauthorizedError"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests — rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/model.RateLimitError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/model.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/states/{id}": {
            "get": {
                "description": "Get specific province details by its code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "states"
                ],
                "summary": "Get state by ID",
                "security": [{"ApiKeyAuth": []}],
                "parameters": [
                    {
                        "type": "string",
                        "description": "State Code (e.g. 11)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Region"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized — invalid API key",
                        "schema": {
                            "$ref": "#/definitions/model.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.APIErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests — rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/model.RateLimitError"
                        }
                    }
                }
            }
        },
        "/states/{id}/cities": {
            "get": {
                "description": "Get list of cities/regencies in a specific province",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "states"
                ],
                "summary": "Get cities in state",
                "security": [{"ApiKeyAuth": []}],
                "parameters": [
                    {
                        "type": "string",
                        "description": "State Code (e.g. 11)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/model.Region"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized — invalid API key",
                        "schema": {
                            "$ref": "#/definitions/model.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.APIErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests — rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/model.RateLimitError"
                        }
                    }
                }
            }
        },
        "/villages/{id}": {
            "get": {
                "description": "Get specific village details by its code",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "villages"
                ],
                "summary": "Get village by ID",
                "security": [{"ApiKeyAuth": []}],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Village Code (e.g. 11.01.01.2001)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/model.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/model.Region"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized — invalid API key",
                        "schema": {
                            "$ref": "#/definitions/model.UnauthorizedError"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/model.APIErrorResponse"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests — rate limit exceeded",
                        "schema": {
                            "$ref": "#/definitions/model.RateLimitError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.APIErrorResponse": {
            "description": "Error API response wrapper",
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Region not found"
                },
                "message": {
                    "type": "string",
                    "example": "NOT_FOUND"
                },
                "status": {
                    "type": "integer",
                    "example": 404
                }
            }
        },
        "model.APIResponse": {
            "description": "Successful API response wrapper",
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string",
                    "example": "SUCCESS"
                },
                "status": {
                    "type": "integer",
                    "example": 200
                }
            }
        },
        "model.Region": {
            "description": "Region information",
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "11"
                },
                "value": {
                    "type": "string",
                    "example": "ACEH"
                }
            }
        },
        "model.RateLimitError": {
            "description": "Rate limit exceeded error response",
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": false
                },
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "RATE_LIMIT_EXCEEDED"
                        },
                        "message": {
                            "type": "string",
                            "example": "Too many requests"
                        }
                    }
                }
            }
        },
        "model.UnauthorizedError": {
            "description": "Invalid API key error response",
            "type": "object",
            "properties": {
                "success": {
                    "type": "boolean",
                    "example": false
                },
                "error": {
                    "type": "object",
                    "properties": {
                        "code": {
                            "type": "string",
                            "example": "INVALID_API_KEY"
                        },
                        "message": {
                            "type": "string",
                            "example": "Invalid API key"
                        }
                    }
                }
            }
        }
    },
    "tags": [
        {
            "description": "Operations regarding provinces",
            "name": "states"
        },
        {
            "description": "Operations regarding cities/regencies",
            "name": "cities"
        },
        {
            "description": "Operations regarding districts",
            "name": "districts"
        },
        {
            "description": "Operations regarding villages",
            "name": "villages"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Geo-ID API",
	Description:      "API for Indonesian Administrative Regions (Provinces, Cities, Districts, Villages).\n\n## Authentication\n\nAll endpoints support an optional **API Key** via the `X-API-KEY` request header.\nProviding a valid key grants a higher rate limit tier (default: 1 000 req/min).\nOmitting the header falls back to the anonymous tier (default: 60 req/min), identified by client IP.\n\n## Rate Limiting\n\nEvery response includes `X-RateLimit-Limit`, `X-RateLimit-Remaining`, and `X-RateLimit-Reset` headers.\nExceeding the limit returns **HTTP 429**. An invalid API key returns **HTTP 401**.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
